package consts

const (
	FormatCreated       = "%s created"
	FormatFound         = "%s found"
	FormatMissing       = "missing %s"
	FormatAlreadyExists = "%s already exists"
	FormatNotFound      = "%s not found"
	FormatInvalid       = "invalid %s"

	Authorized           = "authorized"
	Unauthorized         = "unauthorized"
	MethodNotAllowed     = "method not allowed"
	FriendlyErrorMessage = "an error occurred, please try again later"

	NonNegative = 0
	Positive    = 1

	GET              = "GET"
	POST             = "POST"
	Achievement      = "achievement"
	AchievementID    = "achievement_id"
	Achievements     = "achievements"
	AuthToken        = "auth_token"
	AuthorID         = "author_id"
	Description      = "description"
	Email            = "email"
	Evidence         = "evidence"
	Evidences        = "evidences"
	Experience       = "experience"
	FirstName        = "first_name"
	File             = "file"
	Header           = "header"
	Home             = "home"
	ID               = "id"
	Involvement      = "involvement"
	InvolvementID    = "involvement_id"
	LastName         = "last_name"
	MultimediaType   = "multimedia_type"
	MultimediaTypeID = "multimedia_type_id"
	Page             = "page"
	Password         = "password"
	PictureURL       = "picture_url"
	Quest            = "quest"
	QuestAchievement = "quest_achievement"
	QuestID          = "quest_id"
	QuestType        = "quest_type"
	QuestTypeID      = "quest_type_id"
	Quests           = "quests"
	Reward           = "reward"
	RewardType       = "reward_type"
	RewardTypeID     = "reward_type_id"
	Rewards          = "rewards"
	Title            = "title"
	URL              = "url"
	User             = "user"
	Welcome          = "welcome"
)
