package controller

const (
	formatCreated       = "%s created"
	formatFound         = "%s found"
	formatMissing       = "missing %s"
	formatAlreadyExists = "%s already exists"
	formatNotFound      = "%s not found"
	formatInvalid       = "invalid %s"

	authorized           = "authorized"
	unauthorized         = "unauthorized"
	methodNotAllowed     = "method not allowed"
	friendlyErrorMessage = "an error occurred, please try again later"

	id               = "id"
	achievement      = "achievement"
	achievements     = "achievements"
	achievementID    = "achievement_id"
	involvement      = "involvement"
	user             = "user"
	page             = "page"
	title            = "title"
	description      = "description"
	pictureURL       = "picture_url"
	involvementID    = "involvement_id"
	authorID         = "author_id"
	firstName        = "first_name"
	lastName         = "last_name"
	email            = "email"
	password         = "password"
	_url             = "url"
	multimediaTypeID = "multimedia_type_id"
	multimediaType   = "multimedia_type"
	evidence         = "evidence"
	evidences        = "evidences"
	reward           = "reward"
	rewards          = "rewards"
	rewardType       = "reward_type"
	rewardTypeID     = "reward_type_id"
	quest            = "quest"
	quests           = "quests"
	questID          = "quest_id"
	questType        = "quest_type"
	questTypeID      = "quest_type_id"
	experience       = "experience"
	questAchievement = "quest_achievement"
	home             = "home"
	welcome          = "welcome"

	nonNegative = 0
	positive    = 1

	GET  = "GET"
	POST = "POST"
)
